#*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#*********************************************************************/

name: Docker Image CI

on:  
  workflow_dispatch:
    inputs:
      docker_registry:
            description: 'Registry URL'     
            required: true
            default: 'docker.io/username'
      docker_tag_name:
            description: 'Tag you wish to use on the docker image'     
            required: true
            default: 'rpe:v1'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      
      run: docker build . --file Dockerfile --tag ${{ github.event.inputs.docker_registry }}/${{ github.event.inputs.docker_tag_name }}
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        registry: ${{ github.event.inputs.docker_registry }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: true
    - name: Push the Docker image to the registry
      run: docker push --all-tags ${{ github.event.inputs.docker_registry }}/${{ github.event.inputs.docker_tag_name }}

